PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX coso: <http://w3id.org/coso/v1/contaminoso#>
PREFIX me_egad: <http://sawgraph.spatialai.org/v1/me-egad#>

SELECT * WHERE {
    ?sample a coso:MaterialSample;  # all samples
    		coso:sampleOfMaterialType/rdfs:label ?sampleType;  # with type labels
    		^coso:analyzedSample ?observation. 
    ?observation coso:ofSubstance ?substance. # that were tested for a specific substance
    VALUES ?substance{me_egad:parameter.PFOA_A me_egad:parameter.PFOA me_egad:parameter.PFOA_A_L me_egad:parameter.PFOA_A_BR}  # where the substance is PFOA
} 