# What soil samples have been tested for PFBS? What is the min and max result?
# SUCCESSFULLY TESTED ON FRINK 2026-03-02

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX coso: <http://w3id.org/coso/v1/contaminoso#>
PREFIX dsstox: <http://w3id.org/DSSTox/v1/>

SELECT (max(?value) as ?max_value)  (min(?value) as ?min_value) WHERE {
    ?sample a coso:MaterialSample;  # all samples
    		a coso:SoilSample; # soil samples
    		coso:sampleOfMaterialType/rdfs:label ?sampleType;  # with type labels
    		^coso:analyzedSample ?observation. 
    ?observation coso:ofSubstance ?dtxsid;   # that were tested for a specific substance
    			coso:ofSubstance/rdfs:label ?substanceName;
    			coso:hasResult ?measurement.
    ?measurement coso:measurementValue ?value;
    		coso:measurementUnit/qudt:symbol ?unit.
  FILTER NOT EXISTS {?value owl:sameAs coso:non-detect } # and 
    VALUES ?dtxsid{dsstox:DTXSID5030030} # where the substance is PFBS

} ORDER BY ?value