# What was the detection limit of measurement X?
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX coso: <http://w3id.org/coso/v1/contaminoso#>
PREFIX me_egad_data: <http://w3id.org/sawgraph/v1/me-egad-data#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * 
WHERE{
    VALUES ?measurement{me_egad_data:result.L204794007RE.AAWH.20201030.68259121}
    ?measurement a coso:ContaminantMeasurement;
    			coso:resultAnnotation ?dl.
    ?dl a coso:DetectionLimit;
    	qudt:numericValue ?value;
    	qudt:hasUnit ?unit.   
    
}
