# What known release features exist in this region?

PREFIX kwg-ont: <http://stko-kwg.geog.ucsb.edu/lod/ontology/>
PREFIX coso: <http://w3id.org/coso/v1/contaminoso#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcgeoid: <https://datacommons.org/browser/geoId/>

SELECT * 
WHERE{
    ?releasePoint a coso:ReleaseFeature. 
    ?releasePoint kwg-ont:sfWithin ?region.
    VALUES ?region{dcgeoid:2300571990
}