#  What locations have had multiple reported PFAS releases over time?
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX coso: <http://w3id.org/coso/v1/contaminoso#>

SELECT ?rf ?rfLabel (COUNT(?obs) as ?obsCount) 
WHERE {
	?rf a coso:ReleaseFeature;
   		rdfs:label ?rfLabel.
    ?obs coso:hasFeatureOfInterest ?rf.
} group by ?rf ?rfLabel
HAVING (?obsCount > 1)