# Where did known contaminant releases occur in 2023?

PREFIX coso: <http://w3id.org/coso/v1/contaminoso#>

SELECT * WHERE {
    ?obs a coso:ContaminantReleaseObservation;
        coso:observedTime ?date.
    BIND(YEAR(?date) as ?year)
    FILTER( ?year = 2023)
}